slots:
  1:
    gripper: 0.019
    joints:
    - 0.7854
    - 0.40
    - 0.20
    - -0.60
  2:
    gripper: 0.019
    joints:
    - 2.3562
    - 0.40
    - 0.20
    - -0.60
  3:
    gripper: 0.019
    joints:
    - -2.3562
    - 0.40
    - 0.20
    - -0.60
  4:
    gripper: 0.019
    joints:
    - -0.7854
    - 0.40
    - 0.20
    - -0.60
